# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Future Date
tagline:          'A virtual a11y conf'
description:      'A virtual a11y conference'
url:              http://http://afuturedate.com/
baseurl:          /

author:
  name:           'Lanya Butler'
  url:            https://twitter.com/chiefkikio

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/chiefkikio/AFutureDate

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
